### ISSUE TITLE
MongoDB session

### ISSUE THREAD

**Issue by LaggerIsME** [LaggerIsME/telegrambot_for_chat#2]
# After 1-3 days of working bot can lose connection with MongoDB container, as a result MongoDB drops collections inside of DB and some functions does not work...
## telegram-bot container:
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 954, in _iter
    resp = await method()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/webhook.py", line 139, in post
    results = await self.process_update(update)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/webhook.py", line 190, in process_update
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/handlers/commands.py", line 40, in command_help
    help = await get_instructions('help')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/handlers/commands.py", line 9, in get_instructions
    instruction = instruction['text']
                  ~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
## mongo container:
```
"driver":{"name":"PyMongo","version":"4.3.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"5.4.0-144-generic"},"platform":"CPython 3.8.10.final.0"}}}
{"t":{"$date":"2023-03-21T22:09:07.875+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn46","msg":"dropDatabase - starting","attr":{"db":"config"}}
{"t":{"$date":"2023-03-21T22:09:07.875+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn46","msg":"dropDatabase - dropping collection","attr":{"db":"config","namespace":"config.system.sessions"}}
{"t":{"$date":"2023-03-21T22:09:07.876+00:00"},"s":"I",  "c":"STORAGE",  "id":22206,   "ctx":"conn46","msg":"Deferring table drop for index","attr":{"index":"_id_","namespace":"config.system.sessions","uuid":{"uuid":{"$uuid":"3a9562b8-588c-4d61-809a-20d396e9606b"}},"ident":"index-5--8657858671139101760","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2023-03-21T22:09:07.876+00:00"},"s":"I",  "c":"STORAGE",  "id":22206,   "ctx":"conn46","msg":"Deferring table drop for index","attr":{"index":"lsidTTLIndex","namespace":"config.system.sessions","uuid":{"uuid":{"$uuid":"3a9562b8-588c-4d61-809a-20d396e9606b"}},"ident":"index-6--8657858671139101760","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2023-03-21T22:09:07.876+00:00"},"s":"I",  "c":"STORAGE",  "id":22214,   "ctx":"conn46","msg":"Deferring table drop for collection","attr":{"namespace":"config.system.sessions","ident":"collection-4--8657858671139101760","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2023-03-21T22:09:07.876+00:00"},"s":"I",  "c":"COMMAND",  "id":20336,   "ctx":"conn46","msg":"dropDatabase","attr":{"db":"config","numCollectionsDropped":1}}
{"t":{"$date":"2023-03-21T22:09:07.995+00:00"},"s":"I",  "c":"STORAGE",  "id":22260,   "ctx":"TimestampMonitor","msg":"Removing drop-pending idents with drop timestamps before timestamp","attr":{"timestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2023-03-21T22:09:07.995+00:00"},"s":"I",  "c":"STORAGE",  "id":22237,   "ctx":"TimestampMonitor","msg":"Completing drop for ident","attr":{"ident":"index-5--8657858671139101760","dropTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2023-03-21T22:09:08.003+00:00"},"s":"I",  "c":"STORAGE",  "id":22237,   "ctx":"TimestampMonitor","msg":"Completing drop for ident","attr":{"ident":"index-6--8657858671139101760","dropTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2023-03-21T22:09:08.009+00:00"},"s":"I",  "c":"STORAGE",  "id":22237,   "ctx":"TimestampMonitor","msg":"Completing drop for ident","attr":{"ident":"collection-4--8657858671139101760","dropTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2023-03-21T22:09:08.073+00:00"},"s":"I",  "c":"COMMAND",  "id":20337,   "ctx":"conn46","msg":"dropDatabase - starting","attr":{"db":"filter"}}
{"t":{"$date":"2023-03-21T22:09:08.073+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn46","msg":"dropDatabase - dropping collection","attr":{"db":"filter","namespace":"filter.hellos"}}
{"t":{"$date":"2023-03-21T22:09:08.073+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn46","msg":"dropDatabase - dropping collection","attr":{"db":"filter","namespace":"filter.bad_words"}}
{"t":{"$date":"2023-03-21T22:09:08.073+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn46","msg":"dropDatabase - dropping collection","attr":{"db":"filter","namespace":"filter.gifs"}}
{"t":{"$date":"2023-03-21T22:09:08.073+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn46","msg":"dropDatabase - dropping collection","attr":{"db":"filter","namespace":"filter.anecdotes"}}
{"t":{"$date":"2023-03-21T22:09:08.073+00:00"},"s":"I",  "c":"COMMAND",  "id":20338,   "ctx":"conn46","msg":"dropDatabase - dropping collection","attr":{"db":"filter","namespace":"filter.instructions"}}
```

**Comment by LaggerIsME** [comment]
All was solved, when I changed /help command. I don't know why...
